const API=(document.querySelector('meta[name="api-base"]')?.content||'https://devrafikhanbackend.onrender.com/api').replace(/\/$/,'');
let token='';
const readToken=()=>{try{return localStorage.getItem('rafi-token')||''}catch{return ''}};
const clearAuth=()=>{try{localStorage.removeItem('rafi-token');localStorage.removeItem('rafi-name');localStorage.removeItem('rafi-user')}catch{}};
async function whoAmI(){
  const t=readToken();
  if(t){
    try{
      const r=await fetch(API+'/auth/me',{credentials:'include',headers:{Authorization:'Bearer '+t}});
      if(r.ok){const d=await r.json();return d.user||null}
    }catch{}
    clearAuth();
  }
  try{
    const r=await fetch(API+'/auth/me',{credentials:'include'});
    if(!r.ok)return null;
    const d=await r.json();
    if(d.user){token=d.user.token||readToken();try{localStorage.setItem('rafi-user',JSON.stringify(d.user))}catch{}}
    return d.user||null;
  }catch{return null}
}
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const $=s=>document.querySelector(s);let DATA={};
async function api(path,opt={}){const t=readToken();const h={...(opt.headers||{})};if(t)h.Authorization='Bearer '+t;if(!(opt.body instanceof FormData))h['Content-Type']='application/json';const r=await fetch(API+path,{...opt,credentials:'include',headers:h});const d=await r.json().catch(()=>({}));if(r.status===401){clearAuth();location.href='login.html';return null}if(r.status===403)throw new Error(d.message||'Admin permission required');if(!r.ok)throw new Error(d.message||'Request failed');return d}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('on');setTimeout(()=>t.classList.remove('on'),2200)}
function openTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===id))}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>openTab(b.dataset.tab));$('#logout').onclick=()=>{localStorage.removeItem('rafi-token');location.href='login.html'};
const arr=v=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
function featureParse(v){return String(v||'').split('\n').map(x=>x.trim()).filter(Boolean).map(x=>{const[a,b,c]=x.split('|');return{title:a||'',desc:b||'',icon:c||'LucideCode2'}})}
function featurePrint(a){return(a||[]).map(x=>[x.title,x.desc,x.icon].join('|')).join('\n')}
function mediaParse(v){return String(v||'').split('\n').map(x=>x.trim()).filter(Boolean).map(x=>{const[a,b,c]=x.split('|');return{type:a==='video'?'video':'image',url:b||a,caption:c||''}})}
function mediaPrint(a){return(a||[]).map(x=>[x.type,x.url,x.caption||''].join('|')).join('\n')}
function iconify(v){let x=String(v||'').trim().replace(/^<|>$/g,'').replace(/\/$/,'').trim();x=x.replace(/^icon=/,'').replace(/['"]/g,'');if(x.includes(':'))return x;const m=x.match(/^(Bs|Si|Fa|Fi|Md|Tb|Ri|Hi|Bi|Ai|Gi|Io|Lu)(.+)$/);if(!m)return x;const p={Bs:'bootstrap',Si:'simple-icons',Fa:'fa6-solid',Fi:'feather',Md:'material-symbols',Tb:'tabler',Ri:'ri',Hi:'heroicons',Bi:'boxicons',Ai:'ant-design',Gi:'game-icons',Io:'ion',Lu:'lucide'}[m[1]];let n=m[2].replace(/([a-z])([A-Z])/g,'$1-$2').replace(/([A-Z])([A-Z][a-z])/g,'$1-$2').toLowerCase();if(m[1]==='Si')n=n.replace(/^next-dot-js$/,'nextdotjs').replace(/^node-dot-js$/,'nodedotjs');if(m[1]==='Bs')n=n.replace(/-fill$/,'');return p+':'+n}
async function load(){DATA=(await api('/admin/data'))||{};render();const site=(await api('/site'))?.site||{};renderSite(site);loadReactions();loadLove()}
function render(){const p=DATA.projects||[],b=DATA.blogs||[],m=DATA.messages||[],g=DATA.guestbook||[],u=DATA.users||[],r=DATA.reviews||[],c=DATA.comments||[],a=DATA.activities||[],as=DATA.assets||[],icons=DATA.icons||[];$('#sUsers').textContent=u.length;$('#sProjects').textContent=p.length;$('#sMessages').textContent=m.length;$('#sReviews').textContent=r.length;$('#recentActivity').innerHTML=a.slice(0,8).map(x=>`<div class="item"><div><strong>${esc(x.label||x.type)}</strong><br><small>${new Date(x.createdAt).toLocaleString()}</small></div><small>${esc(x.type)}</small></div>`).join('')||'<p class="hint">No activity yet.</p>';
$('#projectList').innerHTML=p.map(x=>`<div class="item"><div><strong>${esc(x.title)}</strong><br><small>${esc(x.category||'Project')} · ${esc(x.year||'')} · ${x.published?'Published':'Draft'}</small></div><div class="actions"><button class="btn btn-outline" onclick='editProject(${JSON.stringify(x)})'>Edit</button><button class="btn btn-outline danger" onclick="del('/admin/projects/${x._id}')">Delete</button></div></div>`).join('');
$('#blogList').innerHTML=b.map(x=>`<div class="item"><div><strong>${esc(x.title)}</strong><br><small>${esc(x.slug)} · ${x.published?'Published':'Draft'}</small></div><div class="actions"><button class="btn btn-outline" onclick='editBlog(${JSON.stringify(x)})'>Edit</button><button class="btn btn-outline danger" onclick="del('/admin/blogs/${x._id}')">Delete</button></div></div>`).join('');
$('#userList').innerHTML=u.map(x=>`<div class="item"><div><strong>${esc(x.name||'User')}</strong><br><small>${esc(x.email)} · ${x.role} · ${x.isActive?'Active':'Disabled'}</small></div><div class="actions"><button class="btn btn-outline" onclick='editUser(${JSON.stringify(x)})'>Edit</button><button class="btn btn-outline danger" onclick="del('/admin/users/${x._id}')">Delete</button></div></div>`).join('');
$('#messageList').innerHTML=m.map(x=>`<div class="item"><div><strong>${esc(x.name)}</strong> · ${esc(x.email)}<br><small>${esc(x.company||'')} · ${esc(x.projectType||'')} · ${new Date(x.createdAt).toLocaleString()}</small><p>${esc(x.message)}</p></div><div><select class="select" onchange="statusUpdate('/admin/messages/${x._id}',this.value)"><option ${x.status==='new'?'selected':''}>new</option><option ${x.status==='read'?'selected':''}>read</option><option ${x.status==='replied'?'selected':''}>replied</option><option ${x.status==='archived'?'selected':''}>archived</option></select><button class="btn btn-outline danger" onclick="del('/admin/messages/${x._id}')">Delete</button></div></div>`).join('');
$('#guestList').innerHTML=g.map(x=>`<div class="item"><div><strong>${esc(x.name)}</strong><br><small>${esc(x.email||'')} · ${new Date(x.createdAt).toLocaleString()}</small><p>${esc(x.message)}</p><div class="hint">Replies: ${(DATA.guestReplies||[]).filter(q=>String(q.guestId)===String(x._id)).length}</div></div><div><select class="select" onchange="statusUpdate('/admin/guestbook/${x._id}',this.value)"><option ${x.status==='pending'?'selected':''}>pending</option><option ${x.status==='approved'?'selected':''}>approved</option><option ${x.status==='rejected'?'selected':''}>rejected</option></select><button class="btn btn-outline" onclick="replyGuest('${x._id}')">Reply</button><button class="btn btn-outline danger" onclick="del('/admin/guestbook/${x._id}')">Delete</button></div></div>`).join('');
$('#reviewList').innerHTML=r.map(x=>`<div class="item"><div><strong>${esc(x.clientName)}</strong> · ${esc(x.company||'')}<br><small>${esc(x.role||'')}</small><p>${esc(x.text)}</p></div><div class="actions"><button class="btn btn-outline" onclick='editReview(${JSON.stringify(x)})'>Edit</button><button class="btn btn-outline danger" onclick="del('/admin/reviews/${x._id}')">Delete</button></div></div>`).join('');
$('#commentList').innerHTML=c.map(x=>`<div class="item"><div><strong>${esc(x.name)}</strong><br><small>${new Date(x.createdAt).toLocaleString()} · likes ${x.likeCount||0}</small><p>${esc(x.text)}</p></div><div class="actions"><button class="btn btn-outline" onclick="replyComment('${x._id}')">Reply</button><button class="btn btn-outline danger" onclick="del('/admin/comments/${x._id}')">Delete</button></div></div>`).join('');
$('#assetList').innerHTML=as.map(x=>`<article class="asset"><div class="asset-preview">${x.type==='video'?'<video controls src="'+esc(x.url)+'"></video>':'<img src="'+esc(x.url)+'" alt="">'} </div><div class="asset-body"><strong>${esc(x.label||x.key)}</strong><div class="hint">${esc(x.key)}</div><div class="actions"><button class="btn btn-outline" onclick='resetAsset(${JSON.stringify(x)})'>Reset</button><button class="btn btn-outline danger" onclick="del('/admin/assets/${x._id}')">Delete</button></div></div></article>`).join('');
$('#iconList').innerHTML=icons.map(x=>`<div class="item"><div><iconify-icon icon="${esc(x.icon)}" style="font-size:24px"></iconify-icon> <strong>${esc(x.label||x.name)}</strong><br><small>${esc(x.name)} · ${esc(x.icon)}</small></div><button class="btn btn-outline danger" onclick="del('/admin/icons/${x._id}')">Delete</button></div>`).join('');
$('#activityList').innerHTML=a.map(x=>`<div class="item"><div><strong>${esc(x.label||x.type)}</strong><br><small>${new Date(x.createdAt).toLocaleString()} · ${esc(x.ipHash||'')}</small></div><small>${esc(JSON.stringify(x.metadata||{}))}</small></div>`).join('')}
async function del(path){if(!confirm('Delete this item?'))return;await api(path,{method:'DELETE'});toast('Deleted');load()}
async function statusUpdate(path,status){await api(path,{method:'PUT',body:JSON.stringify({status})});toast('Updated');load()}
function fill(form,obj){Object.keys(obj||{}).forEach(k=>{if(form.elements[k])form.elements[k].value=Array.isArray(obj[k])?obj[k].join(', '):(obj[k]??'')})}
function newProject(){$('#projectForm').reset();$('#projectForm').elements.id.value=''}
window.editProject=p=>{const f=$('#projectForm');f.reset();fill(f,p);f.id.value=p._id;f.features.value=featurePrint(p.features);f.media.value=mediaPrint(p.media);f.gallery.value=(p.gallery||[]).join('\n');f.techStack.value=(p.techStack||[]).join(', ');f.tags.value=(p.tags||[]).join(', ');f.published.value=String(!!p.published);f.featured.value=String(!!p.featured);openTab('projects')}
$('#projectForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d={title:f.title.value,slug:f.slug.value,category:f.category.value,year:f.year.value,client:f.client.value,role:f.role.value,platform:f.platform.value,heroImage:f.heroImage.value,description:f.description.value,overview:f.overview.value,challenge:f.challenge.value,solution:f.solution.value,achievements:f.achievements.value,liveUrl:f.liveUrl.value,githubUrl:f.githubUrl.value,techStack:arr(f.techStack.value),tags:arr(f.tags.value),gallery:f.gallery.value.split('\n').map(x=>x.trim()).filter(Boolean),media:mediaParse(f.media.value),features:featureParse(f.features.value),published:f.published.value==='true',featured:f.featured.value==='true',order:Number(f.order.value||0)};const id=f.id.value;await api('/admin/projects'+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify(d)});toast('Project saved');newProject();load()}
function newBlog(){$('#blogForm').reset();$('#blogForm').elements.id.value=''}window.editBlog=b=>{const f=$('#blogForm');f.reset();fill(f,b);f.id.value=b._id;f.published.value=String(!!b.published);f.featured.value=String(!!b.featured);openTab('blogs')}
$('#blogForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d={title:f.title.value,slug:f.slug.value,category:f.category.value,coverImage:f.coverImage.value,excerpt:f.excerpt.value,content:f.content.value,published:f.published.value==='true',featured:f.featured.value==='true'};const id=f.id.value;await api('/admin/blogs'+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify(d)});toast('Blog saved');newBlog();load()}
window.editUser=u=>{const name=prompt('Name',u.name||'');if(name===null)return;const email=prompt('Email',u.email||'');if(email===null)return;const role=prompt('Role: admin/editor/guest',u.role||'guest');if(role===null)return;const active=confirm('Keep this user active?');const password=prompt('New password (leave empty to keep current)')||'';api('/admin/users/'+u._id,{method:'PUT',body:JSON.stringify({name,email,role,isActive:active,password})}).then(()=>{toast('User updated');load()})}
function newReview(){$('#reviewForm').reset();$('#reviewForm').elements.id.value=''}window.editReview=r=>{const f=$('#reviewForm');f.reset();fill(f,r);f.id.value=r._id;f.published.value=String(!!r.published);openTab('reviews')}
$('#reviewForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d={clientName:f.clientName.value,role:f.role.value,company:f.company.value,image:f.image.value,reviewLink:f.reviewLink.value,text:f.text.value,order:Number(f.order.value||0),published:f.published.value==='true'};const id=f.id.value;await api('/admin/reviews'+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify(d)});toast('Review saved');newReview();load()}
window.replyGuest=async id=>{const text=prompt('Your reply');if(!text)return;await api('/admin/guestbook/'+id+'/replies',{method:'POST',body:JSON.stringify({name:'Rafi Khan',message:text})});toast('Reply saved');load()}
window.replyComment=async id=>{const text=prompt('Your reply');if(!text)return;await api('/admin/comments/'+id+'/reply',{method:'POST',body:JSON.stringify({name:'Rafi Khan',text})});toast('Reply saved');load()}
$('#uploadForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const r=await api('/admin/upload',{method:'POST',body:fd});toast(r?.asset?'Uploaded to Cloudinary':'Upload failed');e.currentTarget.reset();load()}
window.resetAsset=async a=>{await api('/admin/assets/'+a._id,{method:'PUT',body:JSON.stringify({url:a.fallbackUrl,cloudinaryPublicId:''})});toast('Fallback restored');load()}
$('#iconSearch').oninput=e=>{const q=e.target.value.toLowerCase();const icons=DATA.icons||[];$('#iconResults').innerHTML=icons.filter(x=>(x.name+' '+x.label+' '+x.icon).toLowerCase().includes(q)).slice(0,16).map(x=>`<button type="button" class="icon-option" onclick='pickIcon(${JSON.stringify(x)})'><iconify-icon icon="${esc(x.icon)}"></iconify-icon> ${esc(x.label)}</button>`).join('')}
window.pickIcon=x=>{$('#iconForm').elements.name.value=x.name;$('#iconForm').elements.label.value=x.label;$('#iconForm').elements.icon.value=x.icon}
$('#iconForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;await api('/admin/icons',{method:'POST',body:JSON.stringify({name:f.name.value,label:f.label.value,icon:iconify(f.icon.value),pinned:true})});toast('Icon saved');f.reset();load()}
async function loadReactions(){const r=await api('/admin/reactions/homepage');$('#reactorList').innerHTML=(r?.reactions||[]).map(x=>`<div class="item"><div><strong>${esc(x.visitorName||'Anonymous visitor')}</strong><br><small>${esc(x.visitorEmail||'No email')} · ${new Date(x.createdAt).toLocaleString()}</small></div><small>${esc(x.ipHash||'')}</small></div>`).join('')||'<p class="hint">No reactors yet.</p>'}
async function loadLove(){try{const r=await fetch(API+'/reactions/homepage');const d=await r.json();$('#loveCount').textContent=d.count;$('#baseLove').value=(DATA||{}).baseCount||''}catch{}}
window.saveBaseLove=async()=>{await api('/admin/reactions/homepage',{method:'PUT',body:JSON.stringify({baseCount:Number($('#baseLove').value||0)})});toast('Base love count saved');loadLove()}
function renderSite(s){const f=$('#siteForm');f.innerHTML=[['name','Name'],['role','Role'],['email','Email'],['phone','Phone'],['location','Location'],['signature','Signature']].map(([k,l])=>`<label class="field">${l}<input class="input" name="${k}" value="${esc(s[k]||'')}"></label>`).join('')+`<label class="field wide">Hero eyebrow<input class="input" name="eyebrow" value="${esc(s.heroCopy?.eyebrow||'')}"></label><label class="field wide">Hero title line 1<input class="input" name="titleLineOne" value="${esc(s.heroCopy?.titleLineOne||'')}"></label><label class="field wide">Hero title line 2<input class="input" name="titleLineTwo" value="${esc(s.heroCopy?.titleLineTwo||'')}"></label><label class="field wide">Hero description<textarea class="textarea" name="description">${esc(s.heroCopy?.description||'')}</textarea></label><label class="field wide">Hero quote<textarea class="textarea" name="quote">${esc(s.heroCopy?.quote||'')}</textarea></label><label class="field wide">Tech stack<input class="input" name="stack" value="${esc((s.stack||[]).join(', '))}"></label><div class="actions wide"><button class="btn btn-white">Save site content</button></div>`;f.onsubmit=async e=>{e.preventDefault();const q=e.currentTarget;const heroCopy={...(s.heroCopy||{}),eyebrow:q.eyebrow.value,titleLineOne:q.titleLineOne.value,titleLineTwo:q.titleLineTwo.value,description:q.description.value,quote:q.quote.value};await api('/admin/site',{method:'PUT',body:JSON.stringify({name:q.name.value,role:q.role.value,email:q.email.value,phone:q.phone.value,location:q.location.value,signature:q.signature.value,stack:arr(q.stack.value),heroCopy})});toast('Site content saved');load()}}
(async()=>{const user=await whoAmI();if(!user){location.href='login.html';return}if(!['admin','editor'].includes(user.role)){toast('Admin permission required');setTimeout(()=>location.href='index.html',900);return}load().catch(e=>toast(e.message))})();