const API_BASE=(document.querySelector('meta[name="api-base"]')?.content||'/api').replace(/\/$/,'');
const FALLBACK_PROJECTS=[];
const FALLBACK_SITE={name:'Mohammad Rafi Khan',role:'Full-Stack Software Engineer',email:'',phone:'',location:'Dhaka, Bangladesh',socials:{},stack:['React','Next.js','Node.js','Express','MongoDB','Redis','React Native','TypeScript','Git','VS Code'],heroCopy:{eyebrow:'Hi, I’m Mohammad Rafi Khan',titleLineOne:'Full-Stack',titleLineTwo:'Software Engineer',description:'I build modern websites, web applications and backend systems with clean architecture, practical UX and production-ready engineering.',quote:'I help founders ship software that scales without turning the codebase into a fragile MVP.'},portraitImage:'assets/images/rafi-portrait.webp.b64',portraitColorImage:'assets/images/rafi-portrait.webp.b64',collabImage:'assets/images/rafi-portrait.webp.b64',signature:'Rafi Khan'};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

async function resolveImage(value){if(!value)return'';if(!String(value).endsWith('.b64'))return value;try{const r=await fetch(value);if(!r.ok)return'';const raw=(await r.text()).trim();return 'data:image/webp;base64,'+raw}catch{return''}}
async function api(path,opts={}){try{const r=await fetch(API_BASE+path,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});const data=await r.json().catch(()=>null);if(!r.ok)throw new Error(data?.message||`Request failed (${r.status})`);return data}catch(e){console.warn(e);return null}}
function toast(msg){const t=document.getElementById('toast');if(!t)return;t.textContent=msg;t.classList.add('on');setTimeout(()=>t.classList.remove('on'),2600)}
function setTheme(){const saved=localStorage.getItem('rafi-theme');if(saved==='light')document.body.classList.add('light');const b=document.getElementById('themeToggle');if(b)b.onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('rafi-theme',document.body.classList.contains('light')?'light':'dark')}}
function clock(){const el=document.getElementById('clock');if(!el)return;const d=new Date();let h=d.getHours(),m=d.getMinutes();const ap=h>=12?'PM':'AM';h=h%12||12;el.textContent=`${String(h).padStart(2,'0')} : ${String(m).padStart(2,'0')} ${ap}`}
function renderSocials(site){const el=document.getElementById('socialRail');if(!el)return;const s=site.socials||{};const links=[['Gh',s.github],['in',s.linkedin],['f',s.facebook],['Wa',s.whatsapp],['X',s.x],['▶',s.youtube]];el.innerHTML=links.filter(([,u])=>u).map(([l,u])=>`<a href="${esc(u)}" target="_blank" rel="noreferrer noopener" title="${esc(l)}">${esc(l)}</a>`).join('')}
function renderStack(site){const el=document.getElementById('stackList');if(el)el.innerHTML=(site.stack||[]).map(x=>`<span>${esc(x)}</span>`).join('')}
function applySite(site){const hero=site.heroCopy||{};const eyebrow=document.querySelector('.hero-copy .eyebrow');const title=document.querySelector('.hero-copy h1');const desc=document.querySelector('.hero-description');const quote=document.querySelector('.hero-quote p');if(eyebrow&&hero.eyebrow)eyebrow.textContent=hero.eyebrow;if(title&&hero.titleLineOne)title.innerHTML=`${esc(hero.titleLineOne)}<br/><span>${esc(hero.titleLineTwo||'')}</span>`;if(desc&&hero.description)desc.textContent=hero.description;if(quote&&hero.quote)quote.innerHTML=`“${esc(hero.quote)}”`;const mail=document.querySelector('.contact-float a[href^="mailto:"]');if(mail&&site.email)mail.href=`mailto:${encodeURIComponent(site.email)}`;const p=document.querySelector('.portrait-gray');const pc=document.querySelector('.portrait-svg image');const grayAsset=site.portraitImage||site.portrait||FALLBACK_SITE.portraitImage;const colorAsset=site.portraitColorImage||site.portraitColor||grayAsset;Promise.all([resolveImage(grayAsset),resolveImage(colorAsset)]).then(([gray,color])=>{if(p&&gray)p.src=gray;if(pc&&color)pc.setAttribute('href',color)});const sig=document.querySelector('.signature');if(sig&&site.signature)sig.textContent=site.signature;const collab=document.getElementById('collabPortrait');const collabAsset=site.collabImage||site.portraitImage||site.portrait||grayAsset;if(collab)resolveImage(collabAsset).then(src=>{if(src)collab.src=src})}
function createRing(projects){const ring=document.getElementById('ring');if(!ring)return;const usable=projects.filter(p=>p.heroImage).slice(0,8);ring.innerHTML=usable.map(p=>`<a class="ring-card" href="project.html?slug=${encodeURIComponent(p.slug)}"><img src="${esc(p.heroImage)}" alt="${esc(p.title)}" loading="lazy"></a>`).join('');const cards=[...ring.querySelectorAll('.ring-card')],r=670;cards.forEach((c,i)=>{const a=(Math.PI*2*i/cards.length)-Math.PI/2;gsap.set(c,{x:Math.cos(a)*r,y:Math.sin(a)*70,z:Math.sin(a)*260,rotationY:a*180/Math.PI+90,rotationZ:(i-4)*1.1})});let rot=0;window.addEventListener('mousemove',e=>{if(innerWidth<900)return;gsap.to(ring,{rotationY:(e.clientX/innerWidth-.5)*30+rot,duration:1.1,ease:'power3.out'})});window.addEventListener('wheel',e=>{rot+=e.deltaY*.01;gsap.to(ring,{rotationY:rot,duration:.8,ease:'power2.out'})},{passive:true})}
function renderFeatured(projects){const el=document.getElementById('featuredProjects');if(!el)return;el.innerHTML=projects.slice(0,4).map(p=>`<a class="project-card" href="project.html?slug=${encodeURIComponent(p.slug)}"><div class="project-image">${p.heroImage?`<img src="${esc(p.heroImage)}" alt="${esc(p.title)}" loading="lazy">`:''}<span class="project-arrow">↗</span></div><div class="project-meta">${esc(p.category||'Project')} · ${esc(p.year||'')}</div><div class="project-title">${esc(p.title)}</div></a>`).join('')||'<p class="muted">Projects are being prepared.</p>'}
function renderBrowser(project){if(!project)return;const pv=document.getElementById('browserPreview');if(pv)pv.style.backgroundImage=`url("${String(project.heroImage||'').replace(/"/g,'%22')}")`;const t=document.getElementById('browserTitle');const d=document.getElementById('browserDescription');const l=document.getElementById('browserLink');const u=document.getElementById('browserUrl');if(t)t.textContent=project.title||'';if(d)d.textContent=project.description||project.summary||'';if(l)l.href='project.html?slug='+encodeURIComponent(project.slug||'');if(u)u.textContent=project.liveUrl||'project detail'}
function initPortraitReveal(){const root=document.getElementById('portrait');if(!root||!window.gsap)return;const group=root.querySelector('#blobGroup');if(!group)return;const blobs=[...group.querySelectorAll('circle')];const base=[{x:48,y:52,s:0.35},{x:63,y:43,s:0.28},{x:57,y:63,s:0.24}];gsap.set(group,{transformOrigin:'50% 50%',scale:.35,opacity:0});gsap.set(blobs,(i)=>({cx:base[i].x,cy:base[i].y,r:base[i].s*20}));const enter=()=>gsap.to(group,{scale:1,opacity:1,duration:1,ease:'power3.out'});const leave=()=>gsap.to(group,{scale:.35,opacity:0,duration:.7,ease:'power3.inOut'});root.addEventListener('mouseenter',enter);root.addEventListener('mouseleave',leave);}
async function bootHome(){setTheme();clock();setInterval(clock,1000);const site=(await api('/site'))?.site||FALLBACK_SITE;applySite(site);renderSocials(site);renderStack(site);const projects=(await api('/projects?limit=20'))?.projects||FALLBACK_PROJECTS;createRing(projects);renderFeatured(projects);renderBrowser(projects[0]);initPortraitReveal();if(window.gsap){gsap.from('.hero-copy>*',{y:28,opacity:0,duration:1,stagger:.08,ease:'power3.out',delay:.15});gsap.from('.hero-portrait',{y:25,opacity:0,duration:1.1,ease:'power3.out'})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootHome);else bootHome();
