const API=(document.querySelector('meta[name="api-base"]')?.content||'https://devrafikhanbackend.onrender.com/api').replace(/\/$/,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const token=()=>{try{return localStorage.getItem('rafi-token')||''}catch{return ''}};
const headers=()=>{const h={};const t=token();if(t)h.Authorization='Bearer '+t;return h};
const slug=new URLSearchParams(location.search).get('slug');let BLOG=null;
async function authMe(){try{const r=await fetch(API+'/auth/me',{credentials:'include',headers:headers()});if(!r.ok)return null;return (await r.json()).user||null}catch{return null}}
async function load(){const r=await fetch(API+'/blogs/'+encodeURIComponent(slug||''),{credentials:'include'});const d=await r.json();BLOG=d.blog;if(!BLOG){document.getElementById('post').innerHTML='<h1>Post not found.</h1>';return}document.title=(BLOG.seoTitle||BLOG.title)+' — Mohammad Rafi Khan';document.getElementById('post').innerHTML='<span class="eyebrow">'+esc(BLOG.category||'Insight')+' · '+new Date(BLOG.publishedAt||Date.now()).toLocaleDateString()+'</span><h1 style="font:400 clamp(56px,7vw,94px)/.9 var(--serif);margin:20px 0 32px;letter-spacing:-.05em">'+esc(BLOG.title)+'</h1>'+(BLOG.coverImage?'<img class="post-cover" src="'+esc(BLOG.coverImage)+'" alt="'+esc(BLOG.title)+'">':'')+'<div class="prose" style="margin-top:35px">'+(BLOG.content||'')+'</div>';document.getElementById('postLikeCount').textContent=BLOG.likeCount||0;renderComments(d.comments||[]);
const u=await authMe();if(u){const f=document.getElementById('commentForm');f.elements.name.value=u.name||'';f.elements.email.value=u.email||'';f.elements.name.readOnly=true;f.elements.email.readOnly=true;f.querySelector('textarea').placeholder='Write your comment…'} }
async function likePost(){const r=await fetch(API+'/blogs/'+BLOG._id+'/like',{method:'POST',credentials:'include',headers:headers()});const d=await r.json();if(r.ok)document.getElementById('postLikeCount').textContent=d.likeCount||0}
function renderComments(rows){const el=document.getElementById('comments');el.innerHTML=rows.length?rows.map(x=>'<div class="item" style="display:block;margin-left:'+(x.parentId?'30px':'0')+'"><strong>'+esc(x.name)+'</strong><small class="muted"> · '+new Date(x.createdAt).toLocaleString()+'</small><p>'+esc(x.text)+'</p><button class="btn btn-outline" onclick="likeComment(\''+x._id+'\')">♡ '+(x.likeCount||0)+'</button> <button class="btn btn-outline" onclick="replyComment(\''+x._id+'\')">Reply</button></div>').join(''):'<p class="muted">No comments yet.</p>'}
async function likeComment(id){const r=await fetch(API+'/comments/'+id+'/like',{method:'POST',credentials:'include',headers:headers()});if(r.ok)load()}
window.replyComment=id=>{const f=document.getElementById('commentForm');f.dataset.parentId=id;f.scrollIntoView({behavior:'smooth',block:'center'});f.elements.text.focus();f.elements.text.placeholder='Write a reply...'};
document.getElementById('postLike').onclick=likePost;
document.getElementById('commentForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;const body={name:f.name.value,email:f.email.value,text:f.text.value,parentId:f.dataset.parentId||null};const r=await fetch(API+'/blogs/'+encodeURIComponent(slug)+'/comments',{method:'POST',credentials:'include',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.ok){f.elements.text.value='';delete f.dataset.parentId;load()}};
load().catch(()=>{});