import express from "express";import cors from "cors";import helmet from "helmet";import morgan from "morgan";import mongoose from "mongoose";import bcrypt from "bcryptjs";import jwt from "jsonwebtoken";
const app=express();app.use(helmet({crossOriginResourcePolicy:false}));app.use(cors({origin:true}));app.use(express.json({limit:"12mb"}));app.use(morgan("tiny"));
const secret=process.env.JWT_SECRET||"devrafikhan-local-secret";
const Project=mongoose.models.Project||mongoose.model("Project",new mongoose.Schema({title:String,slug:{type:String,unique:true},category:String,year:String,summary:String,description:String,fullDescription:String,heroImage:String,gallery:[String],liveUrl:String,githubUrl:String,tags:[String],featured:{type:Boolean,default:true},order:{type:Number,default:0}},{timestamps:true}));
const Blog=mongoose.models.Blog||mongoose.model("Blog",new mongoose.Schema({title:String,slug:{type:String,unique:true},category:String,excerpt:String,content:String,coverImage:String,published:{type:Boolean,default:true},publishedAt:{type:Date,default:Date.now}},{timestamps:true}));
const Site=mongoose.models.SiteContent||mongoose.model("SiteContent",new mongoose.Schema({key:{type:String,unique:true},value:mongoose.Schema.Types.Mixed},{timestamps:true}));
const Message=mongoose.models.ContactMessage||mongoose.model("ContactMessage",new mongoose.Schema({name:String,email:String,company:String,projectType:String,message:String,status:{type:String,default:"new"}},{timestamps:true}));
const Guest=mongoose.models.Guestbook||mongoose.model("Guestbook",new mongoose.Schema({name:String,email:String,message:String,approved:{type:Boolean,default:false}},{timestamps:true}));
const User=mongoose.models.User||mongoose.model("User",new mongoose.Schema({name:String,email:{type:String,unique:true},passwordHash:String,role:{type:String,default:"guest"}},{timestamps:true}));
let ready;
async function ensureDb(){if(!ready)ready=mongoose.connect(process.env.MONGODB_URI).then(seed);return ready}
async function seed(){const site={name:"Mohammad Rafi Khan",role:"Full-Stack Software Engineer",email:process.env.PUBLIC_EMAIL||"rafi@webin.agency",phone:"+8801831624571",location:"Dhaka, Bangladesh",github:"https://github.com/MdRafiKhan738",linkedin:"",facebook:"",whatsapp:"https://wa.me/8801831624571",x:"",portrait:"",portraitBw:"",signature:"",stack:["React","Next.js","Node.js","Express","MongoDB","Redis","React Native","TypeScript","Git","VS Code"]};for(const [key,value] of Object.entries(site))await Site.findOneAndUpdate({key},{key,value},{upsert:true});if(!await User.exists({role:"admin"})&&process.env.ADMIN_EMAIL&&process.env.ADMIN_PASSWORD)await User.create({name:"Rafi Admin",email:process.env.ADMIN_EMAIL,passwordHash:await bcrypt.hash(process.env.ADMIN_PASSWORD,12),role:"admin"});if(!await Project.exists({slug:"webin-business-website"}))await Project.insertMany([{title:"Webin — Business Website",slug:"webin-business-website",category:"Web Development",year:"2026",summary:"A conversion-first agency website.",description:"Editorial layout, motion and responsive sections.",fullDescription:"A refined agency website with motion, responsive layouts and a clear conversion path.",heroImage:"https://developerrafikhan.vercel.app/assets/images/projects/softunebd/hero.webp",tags:["HTML","GSAP","Responsive"],order:1},{title:"OneCart — E-Commerce Platform",slug:"onecart-ecommerce",category:"Full-Stack",year:"2026",summary:"MERN commerce experience.",description:"Products, auth, cart, wishlist, reviews and orders.",heroImage:"https://developerrafikhan.vercel.app/assets/images/projects/hoteleasy/hero.webp",tags:["React","Node","MongoDB"],order:2},{title:"AI Workflow Studio",slug:"ai-workflow-studio",category:"AI / Automation",year:"2026",summary:"Lead-generation workflow tooling.",description:"Scraping, enrichment, scoring and outreach workflows.",heroImage:"https://developerrafikhan.vercel.app/assets/images/projects/zinetic/hero.webp",tags:["AI","Automation","APIs"],order:3},{title:"Shadamon Investment Platform",slug:"shadamon-investment",category:"SaaS",year:"2026",summary:"Investment marketplace.",description:"Investor and business-owner marketplace with connects and packages.",heroImage:"https://developerrafikhan.vercel.app/assets/images/projects/wonderscore/hero.webp",tags:["MERN","SaaS","Admin"],order:4}]);if(!await Blog.exists({slug:"building-software-that-lasts"}))await Blog.create({title:"Building software that lasts beyond launch week",slug:"building-software-that-lasts",category:"Engineering",excerpt:"Architecture, communication and shipping.",content:"<p>Good software is the system your team can still understand later.</p><h2>Clarity compounds</h2><p>Small choices around boundaries, naming and observability save time later.</p>",coverImage:"https://developerrafikhan.vercel.app/assets/images/blog/blog-1.webp"})}
const token=u=>jwt.sign({id:u._id.toString(),role:u.role,email:u.email},secret,{expiresIn:"7d"});const auth=(req,res,next)=>{try{req.user=jwt.verify((req.headers.authorization||"").replace(/^Bearer\s+/,""),secret);next()}catch{res.status(401).json({message:"Authentication required"})}};const admin=(req,res,next)=>req.user?.role==="admin"?next():res.status(403).json({message:"Admin only"});
app.get("/api/health",async(_,res)=>{await ensureDb();res.json({ok:true,service:"devrafikhan-api"})});
app.get("/api/site",async(_,res)=>{await ensureDb();const rows=await Site.find({});res.json({site:Object.fromEntries(rows.map(r=>[r.key,r.value]))})});
app.get("/api/projects",async(_,res)=>{await ensureDb();res.json({projects:await Project.find({}).sort({order:1,createdAt:-1})})});
app.get("/api/projects/:slug",async(req,res)=>{await ensureDb();const project=await Project.findOne({slug:req.params.slug});if(!project)return res.status(404).json({message:"Project not found"});res.json({project})});
app.get("/api/blogs",async(_,res)=>{await ensureDb();res.json({blogs:await Blog.find({published:true}).sort({publishedAt:-1})})});
app.get("/api/blogs/:slug",async(req,res)=>{await ensureDb();const blog=await Blog.findOne({slug:req.params.slug,published:true});if(!blog)return res.status(404).json({message:"Post not found"});res.json({blog})});
app.post("/api/contact",async(req,res)=>{await ensureDb();const {name,email,company,projectType,message}=req.body;if(!name||!email||!message)return res.status(400).json({message:"Name, email and message are required"});await Message.create({name,email,company,projectType,message});res.json({success:true})});
app.get("/api/guestbook",async(_,res)=>{await ensureDb();res.json({entries:await Guest.find({approved:true}).sort({createdAt:-1}).limit(40)})});
app.post("/api/guestbook",async(req,res)=>{await ensureDb();const {name,email,message}=req.body;if(!name||!message)return res.status(400).json({message:"Name and message are required"});await Guest.create({name,email,message});res.json({success:true})});
app.post("/api/auth/signup",async(req,res)=>{await ensureDb();const {name,email,password}=req.body;if(!email||!password)return res.status(400).json({message:"Email and password required"});if(await User.exists({email}))return res.status(409).json({message:"Account already exists"});const u=await User.create({name:name||"Guest",email,passwordHash:await bcrypt.hash(password,12)});res.json({token:token(u),user:{id:u._id,name:u.name,email:u.email,role:u.role}})});
app.post("/api/auth/login",async(req,res)=>{await ensureDb();const u=await User.findOne({email:req.body.email});if(!u||!(await bcrypt.compare(req.body.password||"",u.passwordHash)))return res.status(401).json({message:"Invalid credentials"});res.json({token:token(u),user:{id:u._id,name:u.name,email:u.email,role:u.role}})});
app.get("/api/admin/data",auth,admin,async(_,res)=>{await ensureDb();res.json({projects:await Project.find({}).sort({order:1}),blogs:await Blog.find({}).sort({publishedAt:-1}),messages:await Message.find({}).sort({createdAt:-1}),guestbook:await Guest.find({}).sort({createdAt:-1})})});
app.post("/api/admin/projects",auth,admin,async(req,res)=>{await ensureDb();res.json({project:await Project.create(req.body)})});app.put("/api/admin/projects/:id",auth,admin,async(req,res)=>{await ensureDb();res.json({project:await Project.findByIdAndUpdate(req.params.id,req.body,{new:true})})});app.delete("/api/admin/projects/:id",auth,admin,async(req,res)=>{await ensureDb();await Project.findByIdAndDelete(req.params.id);res.json({success:true})});
app.post("/api/admin/blogs",auth,admin,async(req,res)=>{await ensureDb();res.json({blog:await Blog.create(req.body)})});app.delete("/api/admin/blogs/:id",auth,admin,async(req,res)=>{await ensureDb();await Blog.findByIdAndDelete(req.params.id);res.json({success:true})});
app.get("/api/admin/messages",auth,admin,async(_,res)=>{await ensureDb();res.json({messages:await Message.find({}).sort({createdAt:-1})})});app.get("/api/admin/guestbook",auth,admin,async(_,res)=>{await ensureDb();res.json({entries:await Guest.find({}).sort({createdAt:-1})})});app.put("/api/admin/guestbook/:id",auth,admin,async(req,res)=>{await ensureDb();res.json({entry:await Guest.findByIdAndUpdate(req.params.id,req.body,{new:true})})});app.put("/api/admin/site",auth,admin,async(req,res)=>{await ensureDb();for(const [key,value] of Object.entries(req.body))await Site.findOneAndUpdate({key},{key,value},{upsert:true});res.json({success:true})});
const port=process.env.PORT||5050;ensureDb().then(()=>app.listen(port,()=>console.log("DevRafiKhan API on "+port))).catch(err=>{console.error(err);process.exit(1)});